### PR TITLE
enriched docstrings/add alpha95 output to estimate_pole()

### PR DESCRIPTION
**Pull request by Swanson-Hysell**
This commit makes some additions and edits to the smpsite function docstrings. It also adds "alpha95" as a dictionary item that is returned from the estimate_pole() function.

### CODE REVIEW

**Comment by Swanson-Hysell** [comment]
Note that this "alpha95" dictionary addition is necessary for the Sampling_example.ipynb to currently run. It it may make sense to make an updated release after merging this pull request.

**Comment by Swanson-Hysell** [comment]
@facusapienza21 note the change in the `simulate_estimations()` parameters which were:

```
simulate_estimations(params, n_iters=100, ignore_outliers=False, seed=None)
```

with False being changed to "False". I think that this makes sense to be consistent with `estimate_pole` where this value is sent, but is one change that has the potential to cause issue

```
simulate_estimations(params, n_iters=100, ignore_outliers="False", seed=None)
```

**Comment by facusapienza21** [comment]
@Swanson-Hysell now we have the test pipeline and I am thinking in filling it with full coverage tests in the next couple of days. What do you think about integrating these changes after we do that? In order to trigger the automatic run of the tests inside the PR I will have to ask you to close this PR and make a new one, so the GH action is triggered (old PR are not affected by new actions).

**Comment by Swanson-Hysell** [comment]
That sounds good to me. We can leave this pull request open for now and you can let me know here when there is test suite coverage and I can close this PR and open a new one.

**Comment by facusapienza21** [comment]
Hi @Swanson-Hysell ! 

Right now, we are in 87% test coverage, so I think it is a good moment to close this PR and create a new one so we are sure the new code doesn't break any existing piece of software.

**Pull request closed without merging**
